In [1]:
import numpy as np

In [4]:
prices = [3600,4500,2800,2600,130,600,85000,32000,580,250]
new_arr = np.array(prices)
print(new_arr, type(new_arr))

[ 3600  4500  2800  2600   130   600 85000 32000   580   250] <class 'numpy.ndarray'>


In [5]:
# (10,)  means  1 dimension array with 10 elements
print(new_arr.dtype, new_arr.shape)

int64 (10,)


In [8]:
print(np.mean(new_arr))
print(np.max(new_arr))
print(np.min(new_arr))
print(np.std(new_arr))

13206.0
85000
130
25600.002812499846


In [21]:
# Create a 10-sales simulation: prices × random quantities (1–10)
# quantities = np.random.randint(1, 11, size=5) then revenue = prices_arr * quantities

# 1 se 10 ke darmiyan koi bhi aik random number chuna jaye ke wo product kitni baar bika (Quantities).
# Phir keemat (prices_arr) aur quantity (quantities) ko aapas mein multiply kar ke kul kamai (revenue) nikali jaye.

prices_arr = np.array([3600, 4500, 2800, 2600, 130, 600, 85000, 32000, 580, 250])
# Changed size to 10 to match prices_arr length
quantities = np.random.randint(1,11, size = 10)
                               
revenue = prices_arr * quantities

print("Quantities:", quantities)
print("Revenue per item:", revenue)
print("Total Reveue:", np.sum(revenue))

                               
                               
                               


Quantities: [9 1 1 6 9 2 4 1 1 5]
Revenue per item: [ 32400   4500   2800  15600   1170   1200 340000  32000    580   1250]
Total Reveue: 431500


In [11]:
# Find all items where revenue > 1000
# Boolean indexing: revenue[revenue > 1000] — this is how ML filters data.




products = ["Khaadi Lawn","J. Kurta","Peshawari Chappal","Dalda Oil (5L)","National Biryani Masala","Johar Joshanda (Box)","Dawlance Fridge","Audionic Earbuds","Sunsilk Shampoo","Tapal Danedar"]
prices_arr = np.array([3600, 4500, 2800, 2600, 130, 600, 85000, 32000, 580, 250])

# Jab aap revenue > 1000 likhte hain, to NumPy har element ko check karta hai aur aik True/False ki list (Boolean Mask) banata hai.
# Phir revenue[...] sirf un items ko uthata hai jahan jawab True hota hai.

filtered_revenue = revenue[revenue > 1000]
print(filtered_revenue)


[ 21600   9000  19600  18200   3600 340000 256000   4060   2250]


In [12]:
# Reshape a 1D array into a 2D array (rows × columns)
# np.arange(12).reshape(3, 4) — understanding shape is critical for ML later.

# np.arange(12) Kya Karta Hai?Yeh zero (0) se shuru kar ke 12 elements ki aik seedhi (1D) array banata hai:
# .reshape(3, 4) Kya Karta Hai?Yeh is seedhi line ko utha kar aik Matrix (2D array) mein badal deta hai, 
# jisme:3 Rows (lambi lines) hoti hain.4 Columns (khari lines) hote hain.
# Hamare paas 12 elements the.3 × 4 = 12 (Yeh bilkul sahi hai!)






In [18]:
# 1. 0 se 11 tak ki 1D array banayi (Total 12 elements)
original_array = np.arange(12)
print("1D Array:")
print(original_array)
print("Original Shape:", original_array.shape) # Output: (12,)
print("-" * 40)

# 2. Isko 3 rows aur 4 columns mein reshape kiya
matrix_3x4 = original_array.reshape(3,4)
print("2D Array (3 Rows, 4 Columns):")
print(matrix_3x4)

print("New Shape:", matrix_3x4.shape) # Output: (3, 4)
print("-" * 40)

# 3. Aik aur example: 4 rows aur 3 columns
matrix_4x3 = original_array.reshape(4,3)
print("2D Array (4 Rows, 3 Columns):")
print(matrix_4x3)





1D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Original Shape: (12,)
----------------------------------------
2D Array (3 Rows, 4 Columns):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New Shape: (3, 4)
----------------------------------------
2D Array (4 Rows, 3 Columns):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
import numpy as np

prices_arr = np.array([180, 220, 650, 120, 480])
qty        = np.random.randint(1, 11, size=5)
revenue    = prices_arr * qty

print("Quantities are:", qty)
print("Mean price:", np.mean(prices_arr))
print("Total revenue:", np.sum(revenue))
print("High-revenue items:", prices_arr[revenue > 1000])

Quantities are: [3 5 7 4 7]
Mean price: 330.0
Total revenue: 10030
High-revenue items: [220 650 480]
